// Unit tests for the merge engine. No Harper, no WASM.
//
// The Harper-backed half of this — proving that two dictionaries whose `S` means
// different things really do produce the right inflections after merging — lives
// in test/packs.test.js, because it needs a real linter to be worth anything.
import assert from "node:assert/strict";
import { describe, it } from "node:test";

import {
  buildAnnotations, buildPack, canonicalFlags, caseTwins, collectFlags, mergeSources, parseAff,
  parseHunspellSource,
} from "../src/core/index.js";

const source = (name, entries, extra = {}) => ({ name, entries, ...extra });
const entry = (word, flags = null) => ({ word, flags });
const flagsOf = (result) => Object.fromEntries(result.entries.map((e) => [e.word, e.flags]));

describe("canonicalFlags", () => {
  it("puts properties before affixes and is order-independent", () => {
    assert.equal(canonicalFlags([..."Sg~N"]), canonicalFlags([..."N~gS"]));
    assert.equal(canonicalFlags([..."Sg~N"]), "~NSg");
  });

  it("drops duplicates", () => {
    assert.equal(canonicalFlags([..."SSgg"]), "Sg");
  });

  it("returns null for no flags", () => {
    assert.equal(canonicalFlags([]), null);
  });
});

describe("mergeSources", () => {
  it("unions affix flags across sources", () => {
    // D2: more inflections from the same base is low-risk — every form is
    // generated by a rule Harper already trusts.
    const merged = mergeSources([
      source("a", [entry("kubelet", "~NS")]),
      source("b", [entry("kubelet", "~Ng")]),
    ]);
    assert.deepEqual(flagsOf(merged), { kubelet: "~NSg" });
    assert.deepEqual(merged.conflicts, []);
  });

  it("is order-independent for affixes", () => {
    const a = source("a", [entry("kubelet", "~NS")]);
    const b = source("b", [entry("kubelet", "~Ng")]);
    assert.deepEqual(flagsOf(mergeSources([a, b])), flagsOf(mergeSources([b, a])));
  });

  it("treats no property claim as no claim, not as a conflict", () => {
    // A hunspell source has affix flags and no properties at all. Filling that
    // gap from a tagged source is not a disagreement.
    const merged = mergeSources([
      source("hunspell", [entry("kubelet", "S")]),
      source("tagged", [entry("kubelet", "~N")]),
    ]);
    assert.deepEqual(flagsOf(merged), { kubelet: "~NS" });
    assert.deepEqual(merged.conflicts, []);
  });

  it("reports a property disagreement instead of unioning it", () => {
    // Asserting a word is both a noun and a verb is often true and sometimes
    // wrong, and a wrong tag degrades Harper's grammar rules quietly.
    const merged = mergeSources([
      source("a", [entry("triage", "~N")]),
      source("b", [entry("triage", "~V")]),
    ]);
    assert.equal(merged.conflicts.length, 1);
    assert.deepEqual(merged.conflicts[0].sources, [
      { name: "a", flags: "~N" },
      { name: "b", flags: "~V" },
    ]);
    assert.equal(merged.conflicts[0].kind, "property");
    assert.equal(merged.conflicts[0].hard, false);
  });

  it("resolves a reported conflict by source order, not by guessing", () => {
    const merged = mergeSources([
      source("first", [entry("triage", "~N")]),
      source("second", [entry("triage", "~V")]),
    ]);
    assert.equal(flagsOf(merged).triage, "~N");
    assert.equal(merged.conflicts[0].resolved, "~N");
  });

  it("names the source that actually made the winning claim", () => {
    // Source 'bare' supplied the word but claimed nothing, so it is not the
    // source the later disagreement is with.
    const merged = mergeSources([
      source("bare", [entry("triage", "S")]),
      source("noun", [entry("triage", "~N")]),
      source("verb", [entry("triage", "~V")]),
    ]);
    assert.deepEqual(merged.conflicts[0].sources.map((s) => s.name), ["noun", "verb"]);
  });

  it("calls m versus w a hard conflict", () => {
    // 'mass only' and 'mass plus countable' are contradictory claims about the
    // same word. There is no union of them that means anything.
    const merged = mergeSources([
      source("a", [entry("telehealth", "~Nm")]),
      source("b", [entry("telehealth", "~Nw")]),
    ]);
    assert.equal(merged.conflicts[0].kind, "mass");
    assert.equal(merged.conflicts[0].hard, true);
    assert.match(merged.conflicts[0].why, /contradictory/);
  });

  it("does not report identical property sets as a conflict", () => {
    const merged = mergeSources([
      source("a", [entry("kubelet", "~NgS")]),
      source("b", [entry("kubelet", "~NSg")]), // same set, written differently
    ]);
    assert.deepEqual(merged.conflicts, []);
  });

  it("counts each source's marginal contribution", () => {
    // Often the honest answer is that a source is not worth including.
    const merged = mergeSources([
      source("first", [entry("kubelet"), entry("etcd")], { license: "MIT" }),
      source("second", [entry("etcd"), entry("kubectl"), entry("kustomize")]),
    ]);
    assert.deepEqual(merged.contribution, [
      { name: "first", total: 2, added: 2, duplicates: 0, license: "MIT" },
      { name: "second", total: 3, added: 2, duplicates: 1, license: null },
    ]);
  });

  it("de-duplicates within a single source too", () => {
    const merged = mergeSources([source("a", [entry("etcd", "~N"), entry("etcd", "S")])]);
    assert.deepEqual(flagsOf(merged), { etcd: "~NS" });
    assert.deepEqual(merged.contribution[0], {
      name: "a", total: 2, added: 1, duplicates: 1, license: null,
    });
  });

  it("records which sources each word came from", () => {
    const merged = mergeSources([
      source("a", [entry("etcd")]),
      source("b", [entry("etcd")]),
      source("c", [entry("kubelet")]),
    ]);
    const bySource = Object.fromEntries(merged.entries.map((e) => [e.word, e.sources]));
    assert.deepEqual(bySource, { etcd: ["a", "b"], kubelet: ["c"] });
  });

  it("produces byte-identical output for identical input", () => {
    // Determinism is what makes a merge reviewable in a diff.
    const build = () => mergeSources([
      source("a", [entry("zeta", "~NS"), entry("alpha", "~N")]),
      source("b", [entry("mu", "Og"), entry("alpha", "S")]),
    ]);
    assert.equal(JSON.stringify(build()), JSON.stringify(build()));
  });

  it("sorts by code point, so the output does not depend on the locale", () => {
    const merged = mergeSources([source("a", [
      entry("Zulu"), entry("apple"), entry("Alpha"), entry("ähnlich"), entry("QALY"),
    ])]);
    assert.deepEqual(merged.entries.map((e) => e.word), [
      "Alpha", "QALY", "Zulu", "apple", "ähnlich",
    ]);
  });

  it("refuses a source whose flags were never translated", () => {
    // The invariant: hunspell flag letters are private to the .aff that defines
    // them. Merging them raw builds a pack whose inflections are wrong, with
    // nothing anywhere reporting a problem.
    const raw = parseHunspellSource({ dic: "1\nkubelet/MS\n" });
    assert.equal(raw.flagsTranslated, false);
    assert.throws(
      () => mergeSources([source("raw", raw.entries, { flagsTranslated: false })]),
      /untranslated flags/,
    );
  });

  it("accepts a translated hunspell source spread in directly", () => {
    const aff = "SFX M Y 1\nSFX M 0 's .\n";
    const parsed = parseHunspellSource({ dic: "1\nkubelet/M\n", aff });
    const merged = mergeSources([{ name: "en", ...parsed }]);
    assert.deepEqual(flagsOf(merged), { kubelet: "g" }); // M translated to Harper's g
  });

  it("keeps a source with flag-free entries even when untranslated", () => {
    // A plain word list has no flags, so there is nothing to mistranslate.
    const merged = mergeSources([
      source("list", [entry("kubelet"), entry("etcd")], { flagsTranslated: false }),
    ]);
    assert.equal(merged.entries.length, 2);
  });
});

describe("case collisions", () => {
  // Harper keeps one entry per word regardless of case, so two spellings that
  // differ only in case become one and the other silently never matches. Merging
  // six cspell dictionaries produced 624 of these. They are reported, never
  // resolved: `BuildKit` beats `BUILDKIT` but `NIST` beats `Nist`, and no rule
  // gets both right.
  it("reports two spellings that differ only by case", () => {
    const merged = mergeSources([
      source("a", [entry("BuildKit", "Og")]),
      source("b", [entry("BUILDKIT", "OgS")]),
    ]);
    assert.equal(merged.collisions.length, 1);
    assert.deepEqual(merged.collisions[0].words.sort(), ["BUILDKIT", "BuildKit"]);
    assert.deepEqual(merged.collisions[0].sources.sort(), ["a", "b"]);
  });

  it("names the spelling that will be shadowed", () => {
    // Entries are sorted by code point and uppercase sorts first, so the
    // lowercase-later spelling is last in the dictionary and wins.
    const merged = mergeSources([source("a", [entry("BUILDKIT"), entry("BuildKit")])]);
    assert.deepEqual(merged.collisions[0], {
      key: "buildkit",
      words: ["BUILDKIT", "BuildKit"],
      winner: "BuildKit",
      shadowed: ["BUILDKIT"],
      sources: ["a"],
    });
  });

  it("keeps both spellings in the output rather than dropping one", () => {
    // Reported, not resolved — the user chooses.
    const merged = mergeSources([source("a", [entry("chmod"), entry("CHMOD")])]);
    assert.deepEqual(merged.entries.map((e) => e.word), ["CHMOD", "chmod"]);
  });

  it("says nothing when case is consistent", () => {
    const merged = mergeSources([source("a", [entry("kubelet"), entry("Istio")])]);
    assert.deepEqual(merged.collisions, []);
  });

  it("groups three spellings of one word together", () => {
    const merged = mergeSources([source("a", [entry("Nl"), entry("NL"), entry("nl")])]);
    assert.equal(merged.collisions.length, 1);
    assert.deepEqual(merged.collisions[0].shadowed, ["NL", "Nl"]);
    assert.equal(merged.collisions[0].winner, "nl");
  });
});

describe("caseTwins", () => {
  it("maps each word to the other spellings of itself", () => {
    const twins = caseTwins(["BUILDKIT", "BuildKit", "kubelet"]);
    assert.deepEqual(twins.get("BUILDKIT"), ["BuildKit"]);
    assert.deepEqual(twins.get("BuildKit"), ["BUILDKIT"]);
    assert.equal(twins.get("kubelet"), undefined);
  });
});

describe("buildPack over a merged set", () => {
  // The plan expects buildPack to need no changes, because collectFlags and
  // buildAnnotations already union over whatever entries they are given.
  // Asserted rather than assumed: a merged entry carries flags from several
  // sources at once, which is the case that would expose a per-entry assumption.
  const merged = mergeSources([
    source("a", [entry("kubelet", "~NS"), entry("Istio", "Og")]),
    source("b", [entry("kubelet", "~Ng"), entry("deprescribe", "~VGdS")]),
  ]);

  it("collects flags from every source's contribution to an entry", () => {
    assert.deepEqual([...collectFlags(merged.entries)].sort(), [
      "G", "N", "O", "S", "V", "d", "g", "~",
    ]);
  });

  it("declares every flag the merged dictionary uses", () => {
    const annotations = buildAnnotations(merged.entries);
    const declared = new Set([
      ...Object.keys(annotations.affixes), ...Object.keys(annotations.properties),
    ]);
    for (const flag of collectFlags(merged.entries)) {
      assert.ok(declared.has(flag), `flag '${flag}' is not declared`);
    }
  });

  it("builds a pack from merged entries unchanged", () => {
    const { files } = buildPack({
      manifest: {
        author: "Test", version: "1.0.0", description: "Merged", license: "MIT",
      },
      entries: merged.entries,
    });
    // The extra `sources` field a merged entry carries is ignored by the writer.
    assert.equal(files.get("dictionary.dict").split("\n")[1], "Istio/Og");
  });
});

describe("the flag namespace collision", () => {
  // The risk in the plan, made concrete: two dictionaries that both use `S`, for
  // different rules. Read raw, `kubelet/S` and `formulary/S` would end up with
  // the same Harper flag and one of them would inflect wrongly.
  const PLURAL_AFF = [
    "SFX S Y 4",
    "SFX S y ies [^aeiou]y", "SFX S 0 s [aeiou]y", "SFX S 0 es [sxzh]", "SFX S 0 s [^sxzhy]",
  ].join("\n");

  // Same letter, completely different rule: here `S` is `-ness`.
  const NESS_AFF = [
    "SFX S Y 3",
    "SFX S y iness [^aeiou]y", "SFX S 0 ness [aeiou]y", "SFX S 0 ness [^y]",
  ].join("\n");

  it("maps the same letter to different Harper flags per source", () => {
    assert.equal(parseAff(PLURAL_AFF).affixes.get("S").replacements.length, 4);
    const plural = parseHunspellSource({ dic: "1\nformulary/S\n", aff: PLURAL_AFF });
    const ness = parseHunspellSource({ dic: "1\nhappy/S\n", aff: NESS_AFF });
    assert.equal(plural.entries[0].flags, "S"); // Harper's plural
    assert.equal(ness.entries[0].flags, "p"); // Harper's -ness
  });

  it("survives the merge with each source's meaning intact", () => {
    const merged = mergeSources([
      { name: "plural", ...parseHunspellSource({ dic: "1\nformulary/S\n", aff: PLURAL_AFF }) },
      { name: "ness", ...parseHunspellSource({ dic: "1\nhappy/S\n", aff: NESS_AFF }) },
    ]);
    assert.deepEqual(flagsOf(merged), { formulary: "S", happy: "p" });
  });

  it("would collide if the flags were merged raw", () => {
    // Not a wish — a demonstration of what this machinery prevents. Both words
    // come out claiming Harper's plural, and `happy/S` then generates
    // `happies` instead of `happiness`.
    const raw = mergeSources([
      { name: "plural", entries: [entry("formulary", "S")] },
      { name: "ness", entries: [entry("happy", "S")] },
    ]);
    assert.deepEqual(flagsOf(raw), { formulary: "S", happy: "S" });
  });
});
