// GENERATED by tools/sync-flags.mjs -- do not edit by hand.
//
// Flag definitions sliced verbatim from Harper's curated annotations.json
// (Automattic/harper, harper-core/annotations.json, Apache-2.0). A Weirpack's
// annotations.json must define every flag its dictionary.dict uses; we emit
// only the ones a given pack actually references.

export const HARPER_FLAGS = {
  "affixes": {
    "S": {
      "#": "'-(i)(e)s' plural suffix",
      "kind": "suffix",
      "cross_product": true,
      "replacements": [
        {
          "remove": "y",
          "add": "ies",
          "condition": "[^aeiou]y"
        },
        {
          "remove": "",
          "add": "s",
          "condition": "[aeiou]y"
        },
        {
          "remove": "",
          "add": "es",
          "condition": "[sxzh]"
        },
        {
          "remove": "",
          "add": "s",
          "condition": "[^sxzhy]"
        }
      ],
      "target": [
        {
          "if_base": {
            "noun": {}
          },
          "metadata": {
            "noun": {
              "is_plural": true
            }
          }
        },
        {
          "if_base": {
            "verb": {}
          },
          "metadata": {
            "verb": {
              "verb_form": "THIRD_PERSON_SINGULAR"
            }
          }
        }
      ],
      "base_metadata": {}
    },
    "g": {
      "#": "-'s possessive suffix; contraction of 'has' and 'is",
      "//": "mnemonic: 'genitive' is a similar concept to 'possessive'",
      "kind": "suffix",
      "cross_product": true,
      "replacements": [
        {
          "remove": "",
          "add": "'s",
          "condition": "."
        }
      ],
      "target": [
        {
          "metadata": {
            "noun": {
              "is_possessive": true
            }
          }
        }
      ],
      "base_metadata": {
        "noun": {}
      }
    },
    "G": {
      "#": "'-ing' suffix",
      "kind": "suffix",
      "cross_product": true,
      "replacements": [
        {
          "remove": "e",
          "add": "ing",
          "condition": "e"
        },
        {
          "remove": "",
          "add": "ing",
          "condition": "[^e]"
        }
      ],
      "target": [
        {
          "metadata": {
            "verb": {
              "verb_form": "PROGRESSIVE"
            },
            "noun": {
              "is_mass": true
            },
            "adjective": {}
          }
        }
      ],
      "base_metadata": {}
    },
    "d": {
      "#": "'-(e)d' suffix; verb past",
      "kind": "suffix",
      "cross_product": true,
      "replacements": [
        {
          "remove": "",
          "add": "d",
          "condition": "e"
        },
        {
          "remove": "y",
          "add": "ied",
          "condition": "[^aeiou]y"
        },
        {
          "remove": "",
          "add": "ed",
          "condition": "[^ey]"
        },
        {
          "remove": "",
          "add": "ed",
          "condition": "[aeiou]y"
        }
      ],
      "target": [
        {
          "metadata": {
            "adjective": {
              "degree": "Positive"
            }
          }
        },
        {
          "if_base": {
            "verb": {}
          },
          "metadata": {
            "verb": {
              "verb_form": "PAST"
            }
          }
        }
      ],
      "base_metadata": {}
    },
    "Y": {
      "#": "'-ly' suffix",
      "kind": "suffix",
      "cross_product": true,
      "replacements": [
        {
          "remove": "",
          "add": "ly",
          "condition": "."
        }
      ],
      "target": [
        {
          "metadata": {
            "adverb": {
              "is_manner": true
            }
          }
        }
      ],
      "base_metadata": {
        "adjective": {}
      }
    },
    "B": {
      "#": "'-able' suffix",
      "kind": "suffix",
      "cross_product": true,
      "replacements": [
        {
          "remove": "",
          "add": "able",
          "condition": "[^aeiou]"
        },
        {
          "remove": "",
          "add": "able",
          "condition": "ee"
        },
        {
          "remove": "e",
          "add": "able",
          "condition": "[^aeiou]e"
        }
      ],
      "target": [
        {
          "if_base": {
            "verb": {}
          },
          "metadata": {
            "adjective": {
              "degree": "Positive"
            }
          }
        }
      ],
      "base_metadata": {}
    },
    "L": {
      "#": "'-ment' suffix",
      "kind": "suffix",
      "cross_product": true,
      "replacements": [
        {
          "remove": "",
          "add": "ment",
          "condition": "."
        }
      ],
      "target": [],
      "base_metadata": {},
      "rename_ok": true
    },
    "n": {
      "#": "nominalization suffixes: -ion, -ication, -en",
      "kind": "suffix",
      "cross_product": true,
      "replacements": [
        {
          "remove": "e",
          "add": "ion",
          "condition": "e"
        },
        {
          "remove": "y",
          "add": "ication",
          "condition": "y"
        },
        {
          "remove": "",
          "add": "en",
          "condition": "[^ey]"
        }
      ],
      "target": [],
      "base_metadata": {}
    },
    "p": {
      "#": "'-(i)ness' suffix",
      "kind": "suffix",
      "cross_product": true,
      "replacements": [
        {
          "remove": "y",
          "add": "iness",
          "condition": "[^aeiou]y"
        },
        {
          "remove": "",
          "add": "ness",
          "condition": "[aeiou]y"
        },
        {
          "remove": "",
          "add": "ness",
          "condition": "[^y]"
        }
      ],
      "target": [],
      "base_metadata": {},
      "rename_ok": true
    },
    ">": {
      "#": "'-(i)er' comparative suffix; agent suffix. see also 'c' which marks a comparative form",
      "//": "mnemonic: greater than is better; singular of 'Z'",
      "kind": "suffix",
      "cross_product": true,
      "replacements": [
        {
          "remove": "",
          "add": "r",
          "condition": "e"
        },
        {
          "remove": "y",
          "add": "ier",
          "condition": "[^aeiou]y"
        },
        {
          "remove": "",
          "add": "er",
          "condition": "[aeiou]y"
        },
        {
          "remove": "",
          "add": "er",
          "condition": "[^ey]"
        }
      ],
      "target": [
        {
          "if_base": {
            "adjective": {}
          },
          "metadata": {
            "adjective": {
              "degree": "Comparative"
            }
          }
        },
        {
          "if_base": {
            "verb": {}
          },
          "metadata": {
            "noun": {
              "//": "TODO: agent noun: run -> runner"
            }
          }
        }
      ],
      "base_metadata": {}
    },
    "^": {
      "#": "'-(i)est' superlative suffix",
      "//": "mnemonic: the topmost is the best. see also 'u' which marks a superlative form",
      "kind": "suffix",
      "cross_product": false,
      "replacements": [
        {
          "remove": "",
          "add": "st",
          "condition": "e"
        },
        {
          "remove": "y",
          "add": "iest",
          "condition": "[^aeiou]y"
        },
        {
          "remove": "",
          "add": "est",
          "condition": "[aeiou]y"
        },
        {
          "remove": "",
          "add": "est",
          "condition": "[^ey]"
        }
      ],
      "target": [
        {
          "if_base": {
            "adjective": {}
          },
          "metadata": {
            "adjective": {
              "degree": "Superlative"
            }
          }
        }
      ],
      "base_metadata": {}
    },
    "z": {
      "#": "'-ings' suffix",
      "kind": "suffix",
      "cross_product": true,
      "replacements": [
        {
          "remove": "e",
          "add": "ings",
          "condition": "e"
        },
        {
          "remove": "",
          "add": "ings",
          "condition": "[^e]"
        }
      ],
      "target": [],
      "base_metadata": {},
      "rename_ok": true
    },
    "X": {
      "#": "'-ions', '-ications', '-ens' suffixes",
      "kind": "suffix",
      "cross_product": true,
      "replacements": [
        {
          "remove": "e",
          "add": "ions",
          "condition": "e"
        },
        {
          "remove": "y",
          "add": "ications",
          "condition": "y"
        },
        {
          "remove": "",
          "add": "ens",
          "condition": "[^ey]"
        }
      ],
      "target": [],
      "base_metadata": {},
      "rename_ok": true
    },
    "Q": {
      "#": "'-ally' suffix",
      "kind": "suffix",
      "cross_product": true,
      "replacements": [
        {
          "remove": "",
          "add": "ally",
          "condition": "."
        }
      ],
      "target": [
        {
          "metadata": {
            "adverb": {}
          }
        }
      ],
      "base_metadata": {},
      "rename_ok": true
    },
    "f": {
      "#": "'-ful' suffix",
      "kind": "suffix",
      "cross_product": true,
      "replacements": [
        {
          "remove": "",
          "add": "ful",
          "condition": "."
        }
      ],
      "target": [],
      "base_metadata": {}
    },
    "v": {
      "#": "'-ive' suffix",
      "kind": "suffix",
      "cross_product": false,
      "replacements": [
        {
          "remove": "e",
          "add": "ive",
          "condition": "e"
        },
        {
          "remove": "",
          "add": "ive",
          "condition": "[^e]"
        }
      ],
      "target": [],
      "base_metadata": {}
    },
    "r": {
      "#": "'re-' prefix",
      "kind": "prefix",
      "cross_product": true,
      "replacements": [
        {
          "remove": "",
          "add": "re",
          "condition": "."
        }
      ],
      "target": [],
      "base_metadata": {}
    },
    "U": {
      "#": "'un-' prefix",
      "kind": "prefix",
      "cross_product": true,
      "replacements": [
        {
          "remove": "",
          "add": "un",
          "condition": "."
        }
      ],
      "target": [],
      "base_metadata": {}
    },
    "i": {
      "#": "'in-' prefix",
      "kind": "prefix",
      "cross_product": true,
      "replacements": [
        {
          "remove": "",
          "add": "in",
          "condition": "."
        }
      ],
      "target": [],
      "base_metadata": {}
    }
  },
  "properties": {
    "0": {
      "#": "singular noun property",
      "//": "mnemonic: the closest digit to single '1' that's not used for grammatical person",
      "metadata": {
        "noun": {
          "is_singular": true
        }
      }
    },
    "9": {
      "#": "plural noun property",
      "//": "mnemonic: the biggest, most plural digit",
      "metadata": {
        "noun": {
          "is_plural": true
        }
      }
    },
    "~": {
      "#": "common word property",
      "metadata": {
        "common": true
      },
      "rename_ok": true,
      "propagate": true
    },
    "N": {
      "#": "noun property",
      "metadata": {
        "noun": {}
      }
    },
    "O": {
      "#": "proper noun property",
      "propagate": true,
      "metadata": {
        "noun": {
          "is_proper": true
        }
      }
    },
    "V": {
      "#": "verb property",
      "metadata": {
        "verb": {}
      }
    },
    "J": {
      "#": "adjective property",
      "metadata": {
        "adjective": {}
      }
    },
    "R": {
      "#": "adverb property",
      "metadata": {
        "adverb": {}
      }
    },
    "m": {
      "#": "mass noun (only) property",
      "metadata": {
        "noun": {
          "is_mass": true
        }
      }
    },
    "w": {
      "#": "mass + countable noun property",
      "metadata": {
        "noun": {
          "is_countable": true,
          "is_mass": true
        }
      }
    },
    "☁": {
      "#": "abstract noun property",
      "//": "mnemonic: cloud = intangible",
      "metadata": {
        "noun": {
          "is_abstract": true
        }
      }
    },
    "†": {
      "#": "slang/informal/nonstandard (always) property",
      "metadata": {
        "slang": true
      }
    }
  }
};
