// Merging several dictionaries into one set of entries.
//
// The one invariant that matters
// -----------------------------
// Flags must already be in Harper space before anything is merged. Two
// dictionaries' `S` are not the same `S` until each has been through its own
// `.aff` — hunspell flag letters are private to the file that defines them. In
// `dictionary-en`, `M` is the possessive and `S` the plural; another dictionary
// is free to use `M` for `-ment` and `S` for `-ness`. Concatenating raw flag
// fields from two sources produces flags that are all still valid characters and
// now mean the wrong thing: nothing errors, the pack builds, and the generated
// inflections are silently wrong.
//
// That is the worst failure this project can have, so it is enforced rather than
// documented — a source whose flags have not been translated is rejected.
//
// What conflicts mean (D2)
// -----------------------
// Affix flags are unioned. More inflections from the same base is low-risk: the
// forms are generated by rules Harper already trusts, and union is
// order-independent, which is what keeps the output deterministic no matter
// which order the sources arrive in.
//
// Property flags are never silently merged. Unioning them asserts a word is both
// a noun and a verb, which is often true and sometimes wrong, and a wrong
// part-of-speech tag degrades Harper's grammar rules quietly — the exact failure
// this project exists to argue against. So they are reported, the first source
// wins for the output, and the user decides.
//
// A merge that resolves conflicts invisibly is a bulk import wearing a better
// coat.
//
// Browser-safe.
import { HARPER_FLAGS } from "./harper-flags.js";

/**
 * Canonical flag order: properties in Harper's own declaration order, then
 * affixes. Any fixed order would do — what matters is that it is fixed, because
 * byte-identical output for identical input is the difference between a merge
 * you can review in a diff and one you have to take on trust.
 */
const FLAG_ORDER = new Map(
  [...Object.keys(HARPER_FLAGS.properties), ...Object.keys(HARPER_FLAGS.affixes)]
    .map((flag, index) => [flag, index]),
);

const isProperty = (flag) => Object.hasOwn(HARPER_FLAGS.properties, flag);

/** Sort flags into canonical order, dropping duplicates. */
export function canonicalFlags(flags) {
  const unique = [...new Set(flags)];
  unique.sort((a, b) => (FLAG_ORDER.get(a) ?? Infinity) - (FLAG_ORDER.get(b) ?? Infinity)
    || (a < b ? -1 : 1));
  return unique.length ? unique.join("") : null;
}

/**
 * Mass-noun claims that cannot be reconciled.
 *
 * `m` is "mass only", `w` is "mass and countable". They are contradictory claims
 * about the same word and there is no union of them that means anything, so this
 * is always surfaced as a hard conflict rather than resolved by precedence.
 */
const MASS_ONLY = "m";
const MASS_AND_COUNTABLE = "w";

function classifyConflict(a, b) {
  const hard = (a.has(MASS_ONLY) && b.has(MASS_AND_COUNTABLE))
    || (a.has(MASS_AND_COUNTABLE) && b.has(MASS_ONLY));
  return hard
    ? { kind: "mass", hard: true, why: "'m' (mass only) and 'w' (mass + countable) are contradictory claims about the same word" }
    : { kind: "property", hard: false, why: "the sources disagree about what part of speech this is" };
}

/**
 * Two spellings of one word that differ only by case.
 *
 * Harper's dictionary is keyed case-insensitively, so `BUILDKIT` and `BuildKit`
 * are the same key with different values — and **only the later entry matches.**
 * The earlier one imports without error and then silently never fires.
 *
 * Measured, because it is not obvious and it is not documented: with both present
 * the last one in the dictionary wins, whichever that is. Since these entries are
 * sorted by code point and uppercase sorts before lowercase, `BuildKit` beats
 * `BUILDKIT` and `readDir` beats `Readdir` — deterministically, which is what
 * lets this be reported rather than merely warned about.
 *
 * This is not resolved automatically. `BuildKit` is the right spelling and
 * `BUILDKIT` a shouty variant, but `NIST` beats `Nist` and no rule gets both
 * right. Merging six cspell dictionaries produced 101 of these, 19 of which cost
 * a word that the pack claimed to contain.
 *
 * @param entries merged entries, already in final order
 */
export function caseGroups(words) {
  const byKey = new Map();
  for (const word of words) {
    const key = word.toLowerCase();
    if (!byKey.has(key)) byKey.set(key, []);
    byKey.get(key).push(word);
  }
  for (const [key, group] of byKey) {
    if (group.length < 2) byKey.delete(key);
  }
  return byKey;
}

/**
 * The other spellings of each word that differ from it only by case.
 *
 * Used to explain a verification failure: if a word the pack claims to add is
 * still flagged, a case twin is very often the reason.
 */
export function caseTwins(words) {
  const twins = new Map();
  for (const group of caseGroups(words).values()) {
    for (const word of group) {
      twins.set(word, group.filter((other) => other !== word));
    }
  }
  return twins;
}

function findCollisions(entries) {
  const wordsBy = new Map(entries.map((entry) => [entry.word, entry]));
  const collisions = [];
  for (const [key, group] of caseGroups(entries.map((entry) => entry.word))) {
    collisions.push({
      key,
      words: group,
      // Last in the dictionary wins; everything before it is shadowed.
      winner: group[group.length - 1],
      shadowed: group.slice(0, -1),
      sources: [...new Set(group.flatMap((word) => wordsBy.get(word).sources))],
    });
  }
  return collisions;
}

/**
 * Merge N sources into one entry list.
 *
 * Precedence is source order: the first source to make a property claim about a
 * word wins the output, and every disagreement after that is reported.
 *
 * @param sources `[{ name, entries, license?, flagsTranslated? }]`, where
 *        `entries` is `[{ word, flags }]` with flags already in Harper space.
 *        Results from `parseHunspellSource` can be spread in directly.
 * @returns `{ entries, conflicts, collisions, contribution }`
 *   - `entries`      merged, sorted by word; each carries the `sources` it came from
 *   - `conflicts`    property disagreements, in word order, never auto-resolved
 *   - `collisions`   spellings differing only by case, where one will be shadowed
 *   - `contribution` per source: how many words it added that no earlier source had
 */
export function mergeSources(sources) {
  const merged = new Map(); // word -> { word, properties, affixes, sources }
  const conflicts = [];
  const contribution = [];

  for (const [index, source] of sources.entries()) {
    const name = source.name ?? `source ${index + 1}`;

    if (source.flagsTranslated === false && source.entries.some((entry) => entry.flags)) {
      throw new Error(
        `source '${name}' carries untranslated flags. Its .aff defines what its `
        + "flag letters mean, so merging them into another dictionary's flag space "
        + "would silently generate the wrong inflections. Parse it with an .aff, "
        + "or strip its flags first.",
      );
    }

    let added = 0;
    let duplicates = 0;

    for (const entry of source.entries) {
      const flags = [...(entry.flags ?? "")];
      const properties = new Set(flags.filter(isProperty));
      const affixes = flags.filter((flag) => !isProperty(flag));

      const existing = merged.get(entry.word);
      if (!existing) {
        merged.set(entry.word, {
          word: entry.word,
          properties,
          // Which source's property claim is in the output. Not necessarily the
          // first source to supply the word — a source can supply a word with no
          // properties at all, and then it has made no claim to win.
          claimedBy: properties.size ? name : null,
          affixes: new Set(affixes),
          sources: [name],
        });
        added += 1;
        continue;
      }

      duplicates += 1;
      if (!existing.sources.includes(name)) existing.sources.push(name);

      // Affixes: union, unconditionally.
      for (const affix of affixes) existing.affixes.add(affix);

      // Properties: an empty set is not a competing claim, it is no claim, so
      // filling a gap is not a conflict. Two different non-empty claims are.
      if (!properties.size) continue;
      if (!existing.properties.size) {
        existing.properties = properties;
        existing.claimedBy = name;
        continue;
      }
      if (sameSet(existing.properties, properties)) continue;

      const { kind, hard, why } = classifyConflict(existing.properties, properties);
      conflicts.push({
        word: entry.word,
        kind,
        hard,
        why,
        sources: [
          { name: existing.claimedBy, flags: canonicalFlags([...existing.properties]) },
          { name, flags: canonicalFlags([...properties]) },
        ],
        resolved: canonicalFlags([...existing.properties]),
      });
    }

    contribution.push({
      name, total: source.entries.length, added, duplicates, license: source.license ?? null,
    });
  }

  const entries = [...merged.values()]
    .sort(byWord)
    .map(({ word, properties, affixes, sources: from }) => ({
      word,
      flags: canonicalFlags([...properties, ...affixes]),
      sources: from,
    }));

  conflicts.sort(byWord);

  return { entries, conflicts, collisions: findCollisions(entries), contribution };
}

/**
 * Sort by code point, not by locale.
 *
 * `localeCompare` is locale-dependent and would make the output of a merge
 * depend on the machine that ran it.
 */
function byWord(a, b) {
  if (a.word < b.word) return -1;
  return a.word > b.word ? 1 : 0;
}

function sameSet(a, b) {
  return a.size === b.size && [...a].every((value) => b.has(value));
}
