#!/usr/bin/env node
// Regenerates src/core/harper-flags.js from Harper's curated annotations.json.
//
// Weirpacks carry their own annotations.json, but the flag definitions have to
// agree with Harper's or the expansions come out wrong. Rather than guess at
// them, we slice the real definitions out of upstream and commit the subset.
//
//   node tools/sync-flags.mjs path/to/harper-core/annotations.json
//
// Upstream: https://github.com/Automattic/harper/blob/master/harper-core/annotations.json
import { readFile, writeFile } from "node:fs/promises";

// The flags weirsmith knows how to emit. Everything here is copied verbatim from
// upstream; this list only decides how much of the table we carry.
const PROPERTIES = ["~", "N", "O", "V", "J", "R", "m", "w", "0", "9", "☁", "†"];
const AFFIXES = [
  "S", "g", "G", "d", "Y", "B", "L", "n", "p", ">", "^", "z", "X", "Q", "f", "v", "r", "U", "i",
];

const source = process.argv[2];
if (!source) {
  console.error("usage: node tools/sync-flags.mjs <path to harper annotations.json>");
  process.exit(2);
}

const curated = JSON.parse(await readFile(source, "utf8"));
const picked = { affixes: {}, properties: {} };

for (const flag of AFFIXES) {
  const entry = curated.affixes?.[flag];
  if (!entry) throw new Error(`upstream has no affix '${flag}'`);
  picked.affixes[flag] = entry;
}
for (const flag of PROPERTIES) {
  const entry = curated.properties?.[flag];
  if (!entry) throw new Error(`upstream has no property '${flag}'`);
  picked.properties[flag] = entry;
}

const banner = `// GENERATED by tools/sync-flags.mjs -- do not edit by hand.
//
// Flag definitions sliced verbatim from Harper's curated annotations.json
// (Automattic/harper, harper-core/annotations.json, Apache-2.0). A Weirpack's
// annotations.json must define every flag its dictionary.dict uses; we emit
// only the ones a given pack actually references.
`;

const body = `${banner}\nexport const HARPER_FLAGS = ${JSON.stringify(picked, null, 2)};\n`;
await writeFile(new URL("../src/core/harper-flags.js", import.meta.url), body);

console.log(
  `wrote ${AFFIXES.length} affixes + ${PROPERTIES.length} properties to src/core/harper-flags.js`,
);
